#!.venv/bin/python3
import sys

from sssig_rules.schema import Schema
from sssig_rules.util import yaml_dump


def main(args: list[str]) -> int:
    print("# Generated by ./hack/translate/show-schema")
    print(yaml_dump(Schema.model_json_schema()))


if __name__ == "__main__":
    main(sys.argv[1:])
